[2018-09-15 01:28:50] production.ERROR: NotFoundHttpException Route: http://localhost/onlineexams [] []
[2018-09-15 01:28:50] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 01:28:50] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:01:17] production.ERROR: NotFoundHttpException Route: http://localhost/onlineexams [] []
[2018-09-15 02:01:17] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:01:17] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:11:51] production.ERROR: NotFoundHttpException Route: http://localhost/onlineexams [] []
[2018-09-15 02:11:51] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:11:51] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:15:54] production.ERROR: NotFoundHttpException Route: http://localhost/onlinexams [] []
[2018-09-15 02:15:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:15:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:146
Stack trace:
#0 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1021): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(989): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 E:\xampp\htdocs\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 E:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 E:\xampp\htdocs\index.php(48): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2018-09-15 02:36:59] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:36:59] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:37:00] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:37:00] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:37:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:37:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:37:02] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2018-09-15 02:37:02] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function toArray() on null' in E:\xampp\htdocs\app\controllers\OnlineExamsController.php:212
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
